-- Modao CMS schema (Supabase Postgres)
create extension if not exists "pgcrypto";

create table if not exists public.module_configs (
  id uuid primary key default gen_random_uuid(),
  module_key text not null unique,
  display_name text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.content_blocks (
  id uuid primary key default gen_random_uuid(),
  module_key text not null references public.module_configs(module_key) on delete cascade,
  block_key text not null,
  title text,
  body text,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'draft' check (status in ('draft', 'published')),
  published_version bigint not null default 0,
  updated_by uuid,
  updated_at timestamptz not null default now(),
  unique(module_key, block_key, status)
);

create table if not exists public.articles (
  id uuid primary key default gen_random_uuid(),
  module_key text not null references public.module_configs(module_key) on delete cascade,
  slug text not null,
  title text not null,
  summary text,
  cover_url text,
  article_url text,
  content_md text,
  tags text[] not null default '{}',
  sort_order int not null default 0,
  status text not null default 'draft' check (status in ('draft', 'published')),
  published_version bigint not null default 0,
  updated_by uuid,
  updated_at timestamptz not null default now(),
  unique(module_key, slug, status)
);

create table if not exists public.media_assets (
  id uuid primary key default gen_random_uuid(),
  module_key text not null,
  file_name text not null,
  file_path text not null unique,
  public_url text not null,
  mime_type text,
  size_bytes bigint,
  created_by uuid,
  created_at timestamptz not null default now()
);

create table if not exists public.app_users_profile (
  id uuid primary key,
  email text,
  role text not null default 'viewer' check (role in ('owner', 'editor', 'viewer')),
  status text not null default 'active' check (status in ('active', 'disabled')),
  display_name text,
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.publish_versions (
  id bigint generated by default as identity primary key,
  module_key text not null references public.module_configs(module_key) on delete cascade,
  status text not null default 'published' check (status in ('published')),
  notes text,
  snapshot jsonb not null default '{}'::jsonb,
  published_by uuid,
  published_at timestamptz not null default now()
);

create table if not exists public.user_companion_profiles (
  user_id uuid primary key,
  companion_id text not null default 'hui-ming',
  onboarding_completed boolean not null default false,
  onboarding_skipped boolean not null default false,
  checkin_streak int not null default 0,
  last_checkin_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_practice_tasks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  content text not null,
  progress int not null default 0 check (progress >= 0),
  status text not null default 'active' check (status in ('active', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_content_blocks_module_status on public.content_blocks(module_key, status);
create index if not exists idx_articles_module_status on public.articles(module_key, status);
create index if not exists idx_publish_versions_module on public.publish_versions(module_key, id desc);
create index if not exists idx_user_practice_tasks_user_id on public.user_practice_tasks(user_id, created_at);

insert into public.module_configs (module_key, display_name)
values
  ('home', '首页'),
  ('companion', '修法伴侣'),
  ('library', '佛学书库'),
  ('pilgrimage', '朝圣'),
  ('vegan', '茹素'),
  ('forum', '论坛'),
  ('users', '用户管理')
on conflict (module_key) do nothing;
